version: "3.8"
services:
  api:
    build: ./api
    image: kiwi-api:0.0.1
    container_name: kiwi-cc-api
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=kiwi
      - POSTGRES_DB_USER=kiwi
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13.1-alpine
    container_name: kiwi-cc-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/dump.sql:/data/dump.sql
      - ./data/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.0-alpine
    container_name: kiwi-cc-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
